# =================================================================================================
# Global hotkeys (cannot conflict with other hotkeys)
confirm = ['enter', 'right', 'l']
quit = ['q', 'esc']
cd_quit = ['Q']

# movement
list_up = ['up', 'k']
list_down = ['down', 'j']
page_up = ['pgup']
page_down = ['pgdown']
# file panel control
create_new_file_panel = ['ctrl+n']
close_file_panel = ['ctrl+w']
next_file_panel = ['tab', 'L']
previous_file_panel = ['shift+left', 'H']
toggle_file_preview_panel = ['ctrl+f']
open_sort_options_menu = ['s']
toggle_reverse_sort = ['R']
# change focus
focus_on_process_bar = ['b','ctrl+p']
focus_on_sidebar = ['f','ctrl+s']
focus_on_metadata = ['m','ctrl+m']
# create file/directory and rename
file_panel_item_create = ['n']
file_panel_item_rename = ['r']
# file operations
copy_items = ['y']
cut_items = ['x']
paste_items = ['p']
delete_items = ['d', 'delete']
permanently_delete_items = ['D']
# compress and extract
extract_file = ['z']
compress_file = ['Z']
# editor
open_file_with_editor = ['e']
open_current_directory_with_editor = ['E']
# other
pinned_directory = ['P', 'F']
toggle_dot_file = ['.', 'ctrl+h']
change_panel_mode = ['v']
open_help_menu = ['?']
open_command_line = [':']
open_spf_prompt = ['>']
copy_path = ['Y']
copy_present_working_directory = ['c']
toggle_footer = ['ctrl+F']
# =================================================================================================
# Typing hotkeys (can conflict with all hotkeys)
confirm_typing = ['enter']
cancel_typing = ['ctrl+c', 'esc']
# =================================================================================================
# Normal mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
parent_directory = ['h', 'left', 'backspace']
search_bar = ['/']
# =================================================================================================
# Select mode hotkeys (can conflict with other modes, cannot conflict with global hotkeys)
file_panel_select_mode_items_select_down = ['shift+down', 'J']
file_panel_select_mode_items_select_up = ['shift+up', 'K']
file_panel_select_all_items = ['ctrl+a']
